baseURL = "https://hamzamohdzubair.github.io/humco1/"
languageCode = "en-us"
title = "Human Collective"
theme = "roxo"
publishDir = "docs"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Projects"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = ""
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Human Collective | Peace and Justice, Together"
  author = "HMZ"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"
  customCSS = ["css/custom.css"]

  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/changeworld.jpg"
    heading               = "Changing the world. Together."
    tagline               = ""
    primary_button        = "See Our Projects"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "OUR RECENT PROJECTS"
    subtitle  = "Getting the Humanity together for the establishment of Peace and Justice"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Ask a Question"
    primary_button_url  = "contact"
    secondary_button    = "Our Projects"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "Koramangala, Bangalore"
      phone   = "9886074895"
      email   = "contact@humancollective.in"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Twitter"
          url  = "#"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "https://www.facebook.com/human.collective.india/"
        # [[params.footer.social.link]]
        #   name = "Dribbble"
        #   url  = "#"
        # [[params.footer.social.link]]
        #   name = "Instagram"
        #   url  = "#"
      # Footer Service
      [params.footer.service]
        title       = ""
        description = ""